<a href="sd.php">Универсальная структура данных</a><br>
<a href="fifo.php">Очередь</a><br>
<a href="tentotwo.php">Системы счисления</a><br>
<a href="stack.php">Стэк</a><br>
<a href="anagramma.php">Анаграмма</a><br>
<a href="php7.php">PHP7</a><br>
<a href="speed.php">Скорость выполнения</a><br>
<a href="gate.php">Вентили и коннекторы</a><br>
<a href="sort.php">Реализация сортировок</a><br>